# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 503)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 221, 33))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 231, 191))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 101, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.verticalLayout.addWidget(self.lineEdit_1_1)
        self.lineEdit_1_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.verticalLayout.addWidget(self.lineEdit_1_3)
        self.lineEdit_1_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_5.setObjectName("lineEdit_1_5")
        self.verticalLayout.addWidget(self.lineEdit_1_5)
        self.lineEdit_1_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_7.setObjectName("lineEdit_1_7")
        self.verticalLayout.addWidget(self.lineEdit_1_7)
        self.lineEdit_1_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_9.setObjectName("lineEdit_1_9")
        self.verticalLayout.addWidget(self.lineEdit_1_9)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 40, 101, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_1_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.verticalLayout_2.addWidget(self.lineEdit_1_2)
        self.lineEdit_1_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.verticalLayout_2.addWidget(self.lineEdit_1_4)
        self.lineEdit_1_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_6.setObjectName("lineEdit_1_6")
        self.verticalLayout_2.addWidget(self.lineEdit_1_6)
        self.lineEdit_1_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_8.setObjectName("lineEdit_1_8")
        self.verticalLayout_2.addWidget(self.lineEdit_1_8)
        self.lineEdit_1_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_10.setObjectName("lineEdit_1_10")
        self.verticalLayout_2.addWidget(self.lineEdit_1_10)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(140, 20, 54, 12))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 50, 241, 191))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 40, 101, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_2_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_2.setObjectName("lineEdit_2_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2_2)
        self.lineEdit_2_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_4.setObjectName("lineEdit_2_4")
        self.verticalLayout_3.addWidget(self.lineEdit_2_4)
        self.lineEdit_2_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_6.setObjectName("lineEdit_2_6")
        self.verticalLayout_3.addWidget(self.lineEdit_2_6)
        self.lineEdit_2_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_8.setObjectName("lineEdit_2_8")
        self.verticalLayout_3.addWidget(self.lineEdit_2_8)
        self.lineEdit_2_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_10.setObjectName("lineEdit_2_10")
        self.verticalLayout_3.addWidget(self.lineEdit_2_10)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 101, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.verticalLayout_4.addWidget(self.lineEdit_2_1)
        self.lineEdit_2_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_3.setObjectName("lineEdit_2_3")
        self.verticalLayout_4.addWidget(self.lineEdit_2_3)
        self.lineEdit_2_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_5.setObjectName("lineEdit_2_5")
        self.verticalLayout_4.addWidget(self.lineEdit_2_5)
        self.lineEdit_2_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_7.setObjectName("lineEdit_2_7")
        self.verticalLayout_4.addWidget(self.lineEdit_2_7)
        self.lineEdit_2_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_9.setObjectName("lineEdit_2_9")
        self.verticalLayout_4.addWidget(self.lineEdit_2_9)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 231, 191))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(120, 40, 101, 141))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_3_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.verticalLayout_5.addWidget(self.lineEdit_3_2)
        self.lineEdit_3_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_4.setObjectName("lineEdit_3_4")
        self.verticalLayout_5.addWidget(self.lineEdit_3_4)
        self.lineEdit_3_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_6.setObjectName("lineEdit_3_6")
        self.verticalLayout_5.addWidget(self.lineEdit_3_6)
        self.lineEdit_3_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_8.setObjectName("lineEdit_3_8")
        self.verticalLayout_5.addWidget(self.lineEdit_3_8)
        self.lineEdit_3_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_10.setObjectName("lineEdit_3_10")
        self.verticalLayout_5.addWidget(self.lineEdit_3_10)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 40, 101, 141))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_3_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.verticalLayout_6.addWidget(self.lineEdit_3_1)
        self.lineEdit_3_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_3.setObjectName("lineEdit_3_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3_3)
        self.lineEdit_3_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_5.setObjectName("lineEdit_3_5")
        self.verticalLayout_6.addWidget(self.lineEdit_3_5)
        self.lineEdit_3_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_7.setObjectName("lineEdit_3_7")
        self.verticalLayout_6.addWidget(self.lineEdit_3_7)
        self.lineEdit_3_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_9.setObjectName("lineEdit_3_9")
        self.verticalLayout_6.addWidget(self.lineEdit_3_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 54, 12))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 70, 54, 12))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_1_1, self.lineEdit_1_3)
        MainWindow.setTabOrder(self.lineEdit_1_3, self.lineEdit_1_5)
        MainWindow.setTabOrder(self.lineEdit_1_5, self.lineEdit_1_7)
        MainWindow.setTabOrder(self.lineEdit_1_7, self.lineEdit_1_9)
        MainWindow.setTabOrder(self.lineEdit_1_9, self.lineEdit_1_2)
        MainWindow.setTabOrder(self.lineEdit_1_2, self.lineEdit_1_4)
        MainWindow.setTabOrder(self.lineEdit_1_4, self.lineEdit_1_6)
        MainWindow.setTabOrder(self.lineEdit_1_6, self.lineEdit_1_8)
        MainWindow.setTabOrder(self.lineEdit_1_8, self.lineEdit_1_10)
        MainWindow.setTabOrder(self.lineEdit_1_10, self.lineEdit_2_1)
        MainWindow.setTabOrder(self.lineEdit_2_1, self.lineEdit_2_3)
        MainWindow.setTabOrder(self.lineEdit_2_3, self.lineEdit_2_5)
        MainWindow.setTabOrder(self.lineEdit_2_5, self.lineEdit_2_7)
        MainWindow.setTabOrder(self.lineEdit_2_7, self.lineEdit_2_9)
        MainWindow.setTabOrder(self.lineEdit_2_9, self.lineEdit_2_2)
        MainWindow.setTabOrder(self.lineEdit_2_2, self.lineEdit_2_4)
        MainWindow.setTabOrder(self.lineEdit_2_4, self.lineEdit_2_6)
        MainWindow.setTabOrder(self.lineEdit_2_6, self.lineEdit_2_8)
        MainWindow.setTabOrder(self.lineEdit_2_8, self.lineEdit_2_10)
        MainWindow.setTabOrder(self.lineEdit_2_10, self.lineEdit_3_1)
        MainWindow.setTabOrder(self.lineEdit_3_1, self.lineEdit_3_3)
        MainWindow.setTabOrder(self.lineEdit_3_3, self.lineEdit_3_5)
        MainWindow.setTabOrder(self.lineEdit_3_5, self.lineEdit_3_7)
        MainWindow.setTabOrder(self.lineEdit_3_7, self.lineEdit_3_9)
        MainWindow.setTabOrder(self.lineEdit_3_9, self.lineEdit_3_2)
        MainWindow.setTabOrder(self.lineEdit_3_2, self.lineEdit_3_4)
        MainWindow.setTabOrder(self.lineEdit_3_4, self.lineEdit_3_6)
        MainWindow.setTabOrder(self.lineEdit_3_6, self.lineEdit_3_8)
        MainWindow.setTabOrder(self.lineEdit_3_8, self.lineEdit_3_10)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "常用小工具合集"))
        self.groupBox.setTitle(_translate("MainWindow", "Hex2Dec"))
        self.label_5.setText(_translate("MainWindow", "Hex:"))
        self.label_6.setText(_translate("MainWindow", "Dec:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hex2Bin"))
        self.label_7.setText(_translate("MainWindow", "Hex:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Dec2Bin"))
        self.label_10.setText(_translate("MainWindow", "Dec:"))
        self.label_9.setText(_translate("MainWindow", "Bin:"))
        self.label_8.setText(_translate("MainWindow", "Bin:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

